In [1]:
num=int(input("enter a number:"))
print(num)


enter a number:4
4


In [3]:
num=int(input("enter a number:"))
if num>0:
    print("Given number is positive")
else:
    print("Given number is negative")
        

enter a number:9
Given number is positive


In [4]:
num=int(input("enter a number:"))
if num>0:
    print("Given number is positive")

enter a number:-2


In [5]:
num=int(input("enter a number:"))
if num>0:
    print("Given number is positive")
elif num<0:
    print("Given number ids Negative")
else:
    print("Given number is Zero")
    

enter a number:9
Given number is positive


In [6]:
num=int(input("enter a number:"))
if num==0:
    print("Given number is Zero")
else:
    if num>0:
        print("Given number is positive")
    else:
        print("Given number is Negative")

enter a number:0
Given number is Zero


In [7]:
for i in range(0,5,1):
    print(i)
    

0
1
2
3
4


In [8]:
n=int(input("Enter a number:"))
for i in range(0,n+1):
    print(i)
    
    
    

Enter a number:9
0
1
2
3
4
5
6
7
8
9


In [10]:
n=int(input("Enter a number:"))
i=1
while(i<=n):
    print(i)
    i+=1

Enter a number:6
1
2
3
4
5
6


In [12]:
for i in range(5):
    if i==3:
        break
    print(i)

0
1
2


In [15]:
for i in range(5):
    if i==3:
        continue
    print(i)

0
1
2
4


In [14]:
for i in range(5):
    if i==3:
        pass
    print(i)

0
1
2
3
4


In [16]:
l=[]
print(l)
print(type(l))

[]
<class 'list'>


In [18]:
l=[1,2,3]#similar data type values
print(l)

[1, 2, 3]


In [19]:
l=[1,1.5,"ADC"]#multiple data type values
print(l)

[1, 1.5, 'ADC']


In [20]:
l=[1,2,3]
l[2]=4
print(l)

[1, 2, 4]


In [21]:
l.append(5)
print(l)

[1, 2, 4, 5]


In [23]:
l.pop()
print(l)

[1, 2, 4]


In [24]:
l.remove(2)
print(l)

[1, 4]


In [25]:
l=[1,5,2,3,8,5,6,8]
print(sum(l))

38


In [26]:
l=[1,5,2,3,8,5,6,8]
print(l.count(5))

2


In [27]:
print(sorted(l))

[1, 2, 3, 5, 5, 6, 8, 8]


In [28]:
l=[1,5,2,3,8,5,6,8]
l.sort()
print(l)

[1, 2, 3, 5, 5, 6, 8, 8]


In [29]:
l.clear()
print(l)

[]


In [42]:
l=[1,5,2,3,8,5,6,8]
for i in l:
    print(l)

[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]
[1, 5, 2, 3, 8, 5, 6, 8]


In [35]:
d={}
print(d)
print(type(d))

{}
<class 'dict'>


In [37]:
d={"name":"John","Rollno":32}
print(d)

{'name': 'John', 'Rollno': 32}


In [38]:
print(d["name"])

John


In [43]:
print(d.keys())

dict_keys(['name', 'Rollno'])


In [ ]:
### 3RD DAY......

In [3]:
f=open('abc.txt','w')
print('filename:',f.name)
print('filename:',f.mode)
print(f.readable())
print(f.writable())
print(f.closed)
f.close()
print(f.closed)

filename: abc.txt
filename: w
False
True
False
True


In [4]:
with open ('abc.txt',"r") as file:
    content=file.read()
    print(content)

ADITYA DEGREE COLLEGE 
KAKINADA
AP


In [6]:
with open ('abc.txt',"r") as file:
    content=file.read(6)
    print(content)

ADITYA


In [9]:
with open ('abc.txt',"r") as file:
    content=file.readlines()
    print(content)

['ADITYA DEGREE COLLEGE \n', 'KAKINADA\n', 'AP']


In [8]:
with open ('abc.txt',"r") as file:
    content=file.readline()
    print(content)

ADITYA DEGREE COLLEGE 



In [1]:
with open ('abc.txt',"w") as file:
    file.write("aditya degree college")

In [2]:
l=['ADITYA DEGREE COLLEGE \n', 'KAKINADA\n', 'AP']
with open ('abc.txt',"w") as file:
    file.writelines(l)

In [3]:
with open ('abc.txt',"a") as file:
    file.write("533006")
    

In [4]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["yamuna",21,"kakinada"])
    writer.writerow(["devi",24,"durgada"])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3582325470.py, line 6)

In [1]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)


['Name', 'Age', 'City']
['yamuna', '21', 'kakinada']
['devi', '24', 'durgada']


In [ ]:
####  4TH DAY....

In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(100)
%timeit [i**2 for i in l]


18.3 µs ± 720 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
a=np.arange(100)
%timeit a**2

1.94 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating arrays

In [12]:
a=np.array([1,2,3,4,5])  ##one dimensional array
print(a)

[1 2 3 4 5]


In [7]:
print(a.ndim)

1


In [10]:
b=np.array([[1,2,3],[4,5,6]])  ### two dimensional array


In [11]:
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)

2


In [14]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
print(c.ndim)

3


In [16]:
print(a.shape)

(5,)


In [17]:
print(b.shape)

(2, 3)


In [18]:
print(c.shape)

(2, 2, 2)


# Functions for Creating Array

In [19]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [22]:
##using linspace
a=np.linspace(0,1,5) ##5 is seperate
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [29]:
a=np.diag([1,2,3,4,5,6,7])
print(a)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [30]:
print(np.diag(a))

[1 2 3 4 5 6 7]


# Basic Datatype

In [31]:
a=np.arange(10)
print(a.dtype)

int32


In [34]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [37]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Datatype

In [38]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [39]:
a=np.array([True,False])
print(a.dtype)

bool


In [41]:
a=np.array(['KKD','ADC'])
print(a.dtype)   ###unicode string type

<U3


# Indexing And Slicing

In [42]:
a=np.arange(10)
print(a[5])   ##one dimension array

5


In [46]:
a=np.diag([1,2,3,4])
print(a[1,1])    ##two dimensional array

2


# Slicing


In [47]:
a=np.arange (10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
print(a[1:8:2])  ##2 is cut

[1 3 5 7]


In [49]:
a=np.arange(10)
a[5:]=10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


# Copies and viewing

In [50]:
a=np.arange(10)
b=a[::2]                          ###viewing
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [53]:
print(np.shares_memory(a,b))

True


In [54]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [55]:
a=np.arange(10)
b=a[::2].copy()                     #####copying
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [56]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random Number Generator

In [57]:
a=np.random.randint(0,20,15)
print(a)

[15 11 11 15 11  9 17  5  5  5  1 13 14  8  8]


In [59]:
mask=(a%2==0)

In [60]:
mask_a=a[mask]
print(mask_a)

[14  8  8]


In [61]:
a[mask]=-1
print(a)

[15 11 11 15 11  9 17  5  5  5  1 13 -1 -1 -1]


# PANDAS



In [1]:
import pandas as pd 
import numpy as np
pd.__version__ # know the pandas version


'2.0.3'

# Pandas Data structures
# series- one dimensional column
# Data frame- Table with rows+columns

In [2]:
s=pd.Series([1,2,3,]) # one column
print(s)

0    1
1    2
2    3
dtype: int64


In [3]:
df=pd.DataFrame({
    "name": ["yammu","Sai"],
    "age":[12,34]})
df

name  age
0  yammu   12
1    Sai   34

# Reading Data (CSV)

In [6]:
import pandas as pd
df=pd.read_csv(r"C:\Users\YAMUNA\OneDrive\Documents\RESULT (1).csv")
print(df)

          NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0   2.103772e+11          NaN               NaN               0.0   
1   2.103772e+11          NaN               NaN               0.0   
2   2.103772e+11          NaN               NaN               0.0   
3   2.103772e+11          NaN               NaN               0.0   
4   2.103772e+11          NaN               NaN               0.0   
5   2.103772e+11          NaN               NaN               0.0   
6   2.103772e+11          NaN               NaN               0.0   
7   2.103772e+11          NaN               NaN               0.0   
8   2.103772e+11          NaN               NaN               0.0   
9   2.103772e+11          NaN               NaN               0.0   
10  2.103772e+11          NaN               NaN               0.0   
11  2.103772e+11          NaN               NaN               0.0   
12  2.103772e+11          NaN               NaN               0.0   
13  2.103772e+11          NaN     

# writing tha data into files

In [10]:
df.to_csv("data.csv",index=False)
df

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0   2.103772e+11          NaN               NaN               0.0   
1   2.103772e+11          NaN               NaN               0.0   
2   2.103772e+11          NaN               NaN               0.0   
3   2.103772e+11          NaN               NaN               0.0   
4   2.103772e+11          NaN               NaN               0.0   
5   2.103772e+11          NaN               NaN               0.0   
6   2.103772e+11          NaN               NaN               0.0   
7   2.103772e+11          NaN               NaN               0.0   
8   2.103772e+11          NaN               NaN               0.0   
9   2.103772e+11          NaN               NaN               0.0   
10  2.103772e+11          NaN               NaN               0.0   
11  2.103772e+11          NaN               NaN               0.0   
12  2.103772e+11          NaN               NaN               0.0   
13  2.103772e+11          NaN               NaN               0.0   
14  2.103772e+11          NaN               NaN               0.0   
15  2.103772e+11          NaN               NaN               0.0   
16  2.103772e+11          NaN               NaN               0.0   
17  2.103772e+11          NaN               NaN               0.0   
18  2.103772e+11          NaN               NaN               0.0   
19  2.103772e+11          NaN               NaN               0.0   
20  2.103772e+11          NaN               NaN               0.0   
21  2.103872e+11          NaN               NaN               0.0   
22  2.102172e+11          NaN               NaN               0.0   
23  2.103772e+11          NaN               NaN               0.0   
24  2.103772e+11          NaN               NaN               0.0   
25  2.103772e+11          NaN               NaN               0.0   
26  2.103772e+11          NaN               NaN               0.0   
27  2.102172e+11          NaN               NaN               0.0   
28  2.103772e+11          NaN               NaN               0.0   
29  2.103772e+11          NaN               NaN               0.0   
30  2.103772e+11          NaN               NaN               0.0   
31  2.102172e+11          NaN               NaN               0.0   
32  2.103772e+11          NaN               NaN               0.0   
33  2.103772e+11          NaN               NaN               0.0   
34  2.103772e+11          NaN               NaN               0.0   
35  2.103772e+11          NaN               NaN               0.0   
36  2.103772e+11          NaN               NaN               0.0   
37  2.102172e+11          NaN               NaN               0.0   
38  2.103772e+11          NaN               NaN               0.0   
39  2.103772e+11          NaN               NaN               0.0   
40  2.103772e+11          NaN               NaN               0.0   
41  2.103772e+11          NaN               NaN               0.0   
42  2.103772e+11          NaN               NaN               0.0   
43  2.102172e+11          NaN               NaN               0.0   
44  2.103772e+11          NaN               NaN               0.0   
45  2.103772e+11          NaN               NaN               0.0   
46           NaN     ANALYSIS               NaN               NaN   
47           NaN    "O" GRADE               0.0               0.0   
48           NaN   "A+" GRADE               0.0               NaN   
49           NaN    "A" GRADE               0.0               NaN   
50           NaN   "B+" GRADE               0.0               NaN   
51           NaN    "B" GRADE               0.0               NaN   
52           NaN    "C" GRADE               0.0               NaN   
53           NaN    "D" GRADE               0.0               NaN   
54           NaN    "F" GRADE               0.0               NaN   

    MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0                NaN               0.0                    NaN   
1              

# Exploring Data

In [11]:
df.head()

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0  2.103772e+11          NaN               NaN               0.0   
1  2.103772e+11          NaN               NaN               0.0   
2  2.103772e+11          NaN               NaN               0.0   
3  2.103772e+11          NaN               NaN               0.0   
4  2.103772e+11          NaN               NaN               0.0   

   MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0               NaN               0.0                    NaN   
1               NaN               0.0                    NaN   
2               NaN               0.0                    NaN   
3               NaN               0.0                    NaN   
4               NaN               0.0                    NaN   

   CSV6AGrade points  COMPUTER SCIENCE V 6A PRACTICALS  CS6APGrade points  \
0                0.0                               NaN                0.0   
1                0.0                               NaN                0.0   
2                0.0                               NaN                0.0   
3                0.0                               NaN                0.0   
4                0.0                               NaN                0.0   

   ...  AIRV6CGrade points  AI AND ROBOTICS V 6C PRACTICALS  \
0  ...                 0.0                              NaN   
1  ...                 0.0                              NaN   
2  ...                 0.0                              NaN   
3  ...                 0.0                              NaN   
4  ...                 0.0                              NaN   

   AIRV6CPGrade points  AI AND ROBOTICS V 7C  AIRV7CGrade points  \
0                  0.0                   NaN                 0.0   
1                  0.0                   NaN                 0.0   
2                  0.0                   NaN                 0.0   
3                  0.0                   NaN                 0.0   
4                  0.0                   NaN                 0.0   

   AI AND ROBOTICS V 7C PRACTICALS  AIRV7CPGrade points  CGPA  PASS or FAIL  \
0                              NaN                  0.0   0.0          FAIL   
1                              NaN                  0.0   0.0          FAIL   
2                              NaN                  0.0   0.0          FAIL   
3                              NaN                  0.0   0.0          FAIL   
4                              NaN                  0.0   0.0          FAIL   

   NO OF BACKLOGS  
0            10.0  
1            10.0  
2            10.0  
3            10.0  
4            10.0  

[5 rows x 25 columns]

In [12]:
df.tail()

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  MATHEMATICS V 7A  \
50     NaN   "B+" GRADE               0.0               NaN               0.0   
51     NaN    "B" GRADE               0.0               NaN               0.0   
52     NaN    "C" GRADE               0.0               NaN               0.0   
53     NaN    "D" GRADE               0.0               NaN               0.0   
54     NaN    "F" GRADE               0.0               NaN               0.0   

    MV7AGrade points  COMPUTER SCIENCE V 6A  CSV6AGrade points  \
50               NaN                    0.0                NaN   
51               NaN                    0.0                NaN   
52               NaN                    0.0                NaN   
53               NaN                    0.0                NaN   
54               NaN                    0.0                NaN   

    COMPUTER SCIENCE V 6A PRACTICALS  CS6APGrade points  ...  \
50                               0.0                NaN  ...   
51                               0.0                NaN  ...   
52                               0.0                NaN  ...   
53                               0.0                NaN  ...   
54                               0.0                NaN  ...   

    AIRV6CGrade points  AI AND ROBOTICS V 6C PRACTICALS  AIRV6CPGrade points  \
50                 NaN                              0.0                  NaN   
51                 NaN                              0.0                  NaN   
52                 NaN                              0.0                  NaN   
53                 NaN                              0.0                  NaN   
54                 NaN                              0.0                  NaN   

    AI AND ROBOTICS V 7C  AIRV7CGrade points  AI AND ROBOTICS V 7C PRACTICALS  \
50                   0.0                 NaN                              0.0   
51                   0.0                 NaN                              0.0   
52                   0.0                 NaN                              0.0   
53                   0.0                 NaN                              0.0   
54                   0.0                 NaN                              0.0   

    AIRV7CPGrade points  CGPA  PASS or FAIL  NO OF BACKLOGS  
50                  NaN   NaN           NaN             NaN  
51                  NaN   NaN           NaN             NaN  
52                  NaN   NaN           NaN             NaN  
53                  NaN   NaN           NaN             NaN  
54                  NaN   NaN           NaN             NaN  

[5 rows x 25 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   NUMBER                            46 non-null     float64
 1   STUDENT NAME                      9 non-null      object 
 2   MATHEMATICS V 6A                  8 non-null      float64
 3   MV6AGrade points                  47 non-null     float64
 4   MATHEMATICS V 7A                  8 non-null      float64
 5   MV7AGrade points                  47 non-null     float64
 6   COMPUTER SCIENCE V 6A             8 non-null      float64
 7   CSV6AGrade points                 47 non-null     float64
 8   COMPUTER SCIENCE V 6A PRACTICALS  8 non-null      float64
 9   CS6APGrade points                 47 non-null     float64
 10  COMPUTER SCIENCE V 7A             8 non-null      float64
 11  CSV7AGrade points                 47 non-null     float64
 12  COMPUTER S

In [16]:
df.shape

(55, 25)

In [17]:
df.index

RangeIndex(start=0, stop=55, step=1)

In [18]:
df.dtypes

NUMBER                              float64
STUDENT NAME                         object
MATHEMATICS V 6A                    float64
MV6AGrade points                    float64
MATHEMATICS V 7A                    float64
MV7AGrade points                    float64
COMPUTER SCIENCE V 6A               float64
CSV6AGrade points                   float64
COMPUTER SCIENCE V 6A PRACTICALS    float64
CS6APGrade points                   float64
COMPUTER SCIENCE V 7A               float64
CSV7AGrade points                   float64
COMPUTER SCIENCE V 7A PRACTICALS    float64
CSV7APGrade points                  float64
AI AND ROBOTICS V 6C                float64
AIRV6CGrade points                  float64
AI AND ROBOTICS V 6C PRACTICALS     float64
AIRV6CPGrade points                 float64
AI AND ROBOTICS V 7C                float64
AIRV7CGrade points                  float64
AI AND ROBOTICS V 7C PRACTICALS     float64
AIRV7CPGrade points                 float64
CGPA                            

In [22]:
df.CGPA

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
30    0.0
31    0.0
32    0.0
33    0.0
34    0.0
35    0.0
36    0.0
37    0.0
38    0.0
39    0.0
40    0.0
41    0.0
42    0.0
43    0.0
44    0.0
45    0.0
46    NaN
47    0.0
48    NaN
49    NaN
50    NaN
51    NaN
52    NaN
53    NaN
54    NaN
Name: CGPA, dtype: float64

In [24]:
df[['CGPA','PASS or FAIL']]

CGPA PASS or FAIL
0    0.0         FAIL
1    0.0         FAIL
2    0.0         FAIL
3    0.0         FAIL
4    0.0         FAIL
5    0.0         FAIL
6    0.0         FAIL
7    0.0         FAIL
8    0.0         FAIL
9    0.0         FAIL
10   0.0         FAIL
11   0.0         FAIL
12   0.0         FAIL
13   0.0         FAIL
14   0.0         FAIL
15   0.0         FAIL
16   0.0         FAIL
17   0.0         FAIL
18   0.0         FAIL
19   0.0         FAIL
20   0.0         FAIL
21   0.0         FAIL
22   0.0         FAIL
23   0.0         FAIL
24   0.0         FAIL
25   0.0         FAIL
26   0.0         FAIL
27   0.0         FAIL
28   0.0         FAIL
29   0.0         FAIL
30   0.0         FAIL
31   0.0         FAIL
32   0.0         FAIL
33   0.0         FAIL
34   0.0         FAIL
35   0.0         FAIL
36   0.0         FAIL
37   0.0         FAIL
38   0.0         FAIL
39   0.0         FAIL
40   0.0         FAIL
41   0.0         FAIL
42   0.0         FAIL
43   0.0         FAIL
44   0.0         FAIL
45   0.0         FAIL
46   NaN          NaN
47   0.0          NaN
48   NaN          NaN
49   NaN          NaN
50   NaN          NaN
51   NaN          NaN
52   NaN          NaN
53   NaN          NaN
54   NaN          NaN

# Missing values

In [25]:
df.isnull()

NUMBER  STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0    False          True              True             False   
1    False          True              True             False   
2    False          True              True             False   
3    False          True              True             False   
4    False          True              True             False   
5    False          True              True             False   
6    False          True              True             False   
7    False          True              True             False   
8    False          True              True             False   
9    False          True              True             False   
10   False          True              True             False   
11   False          True              True             False   
12   False          True              True             False   
13   False          True              True             False   
14   False          True              True             False   
15   False          True              True             False   
16   False          True              True             False   
17   False          True              True             False   
18   False          True              True             False   
19   False          True              True             False   
20   False          True              True             False   
21   False          True              True             False   
22   False          True              True             False   
23   False          True              True             False   
24   False          True              True             False   
25   False          True              True             False   
26   False          True              True             False   
27   False          True              True             False   
28   False          True              True             False   
29   False          True              True             False   
30   False          True              True             False   
31   False          True              True             False   
32   False          True              True             False   
33   False          True              True             False   
34   False          True              True             False   
35   False          True              True             False   
36   False          True              True             False   
37   False          True              True             False   
38   False          True              True             False   
39   False          True              True             False   
40   False          True              True             False   
41   False          True              True             False   
42   False          True              True             False   
43   False          True              True             False   
44   False          True              True             False   
45   False          True              True             False   
46    True         False              True              True   
47    True         False             False             False   
48    True         False             False              True   
49    True         False             False              True   
50    True         False             False              True   
51    True         False             False              True   
52    True         False             False              True   
53    True         False             False              True   
54    True         False             False              True   

    MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0               True             False                   True   
1               True             False                   True   
2               True             False                   True   
3               True             False                   True   
4               True             False                   True   
5               True         

In [31]:
df=pd.DataFrame({
    "name": ["yammu","Sai","devi"],
    "age":[12,34,None]
})
df

name   age
0  yammu  12.0
1    Sai  34.0
2   devi   NaN

In [32]:
df.isnull().sum()

name    0
age     1
dtype: int64

In [33]:
df[df.isnull().any(axis=1)]

name  age
2  devi  NaN

In [36]:
df['age']=df['age'].fillna(df['age'].mean())
print(df)

    name   age
0  yammu  12.0
1    Sai  34.0
2   devi  23.0


In [39]:
df_clean=df.dropna()
df_clean

name   age
0  yammu  12.0
1    Sai  34.0
2   devi  23.0

# Duplicates

In [40]:
df=pd.DataFrame({
    "name": ["yammu","Sai","yammu"],
    "age":[12,34,12] 
})
df

name  age
0  yammu   12
1    Sai   34
2  yammu   12

In [41]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [42]:
df[df.duplicated()]

name  age
2  yammu   12

In [43]:
df=df.drop_duplicates()
df

name  age
0  yammu   12
1    Sai   34

# statistics

In [17]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\YAMUNA\Downloads\data.csv")
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR       A      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR       A       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569     95  
1  9347791232     97  
2  9676976652     90  
3  7382934586     85  
4  9182532802     96  
5  6300408089     90  
6  7386015549     94  
7  8466845651     89  
8  8397941799     90  
9  7386803023     93

In [10]:
df['MARKS'].mean()


91.9

In [11]:
df['MARKS'].max()

97

In [12]:
df['MARKS'].describe()

count    10.000000
mean     91.900000
std       3.725289
min      85.000000
25%      90.000000
50%      91.500000
75%      94.750000
max      97.000000
Name: MARKS, dtype: float64

In [13]:
df.NAME[df.MARKS==df.MARKS.max()]

1    P.Devi
Name: NAME, dtype: object

In [14]:
df.count()

NAME                    10
CLASS                   10
SECTION                 10
ROLLNO                  10
               EMAIL    10
PHNO                    10
MARKS                   10
dtype: int64

In [15]:
df['MARKS'].nunique

<bound method IndexOpsMixin.nunique of 0    95
1    97
2    90
3    85
4    96
5    90
6    94
7    89
8    90
9    93
Name: MARKS, dtype: int64>

In [16]:
df['MARKS'].value_counts()

MARKS
90    3
95    1
97    1
85    1
96    1
94    1
89    1
93    1
Name: count, dtype: int64

# String cleaning



In [6]:
import pandas as pd
import numpy as np


In [10]:
df=pd.read_csv(r"C:\Users\YAMUNA\Downloads\data (1).csv")
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR       A      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR       A       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569     95  
1  9347791232     97  
2  9676976652     90  
3  7382934586     85  
4  9182532802     96  
5  6300408089     90  
6  7386015549     94  
7  8466845651     89  
8  8397941799     90  
9  7386803023     93

In [12]:
df["NAME"]=df["NAME"].str.lower()
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        b.yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          p.devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        j.ramya    AIR       A      52      jivvireddyramyasri@gmailcom   
3     k.prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   k.v. niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  k.sri niharika   AIR       A       9       karresriniharika@gmail.com   
6        y.kaveri   AIR       A       3        yendamurikaveri@gmail.com   
7         p.durga   AIR       A      24              durgarani@gmail.com   
8        p.akhila   AIR       A      29            bottaakhila@gmail.com   
9       p.neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569     95  
1  9347791232     97  
2  9676976652     90  
3  7382934586     85  
4  9182532802     96  
5  6300408089     90  
6  7386015549     94  
7  8466845651     89  
8  8397941799     90  
9  7386803023     93

# Concate DataFrames

In [16]:
US_weather=pd.DataFrame({
    "city":["New York","Chicago","Orlando"],
    "Temperature":[32,45,35]
})
US_weather

city  Temperature
0  New York           32
1   Chicago           45
2   Orlando           35

In [18]:
India_weather=pd.DataFrame({
    "city":["Mumbai","AP","Chennai"],
    "Temperature":[39,46,20]
})
India_weather

city  Temperature
0   Mumbai           39
1       AP           46
2  Chennai           20

In [21]:

import pandas as pd
df=pd.concat([India_weather,US_weather])
df

city  Temperature
0    Mumbai           39
1        AP           46
2   Chennai           20
0  New York           32
1   Chicago           45
2   Orlando           35

In [23]:
df=pd.concat([India_weather,US_weather],axis=1)
df

city  Temperature      city  Temperature
0   Mumbai           39  New York           32
1       AP           46   Chicago           45
2  Chennai           20   Orlando           35

# merge Dataframes

In [24]:
temp_df=pd.DataFrame({
    "city":["New York","Chicago","Orlando"],
    "Temperature":[32,45,35]
})
temp_df

city  Temperature
0  New York           32
1   Chicago           45
2   Orlando           35

In [25]:
humidity_df=pd.DataFrame({
    "city":["Mumbai","AP","Chennai"],
    "humidity":[39,46,20]
})
humidity_df

city  humidity
0   Mumbai        39
1       AP        46
2  Chennai        20

In [27]:
df=pd.merge(temp_df,humidity_df,on="city")
dfdf

Empty DataFrame
Columns: [city, Temperature, humidity]
Index: []

In [28]:
df=pd.merge(temp_df,humidity_df,on="city",how="outer")
df

city  Temperature  humidity
0  New York         32.0       NaN
1   Chicago         45.0       NaN
2   Orlando         35.0       NaN
3    Mumbai          NaN      39.0
4        AP          NaN      46.0
5   Chennai          NaN      20.0

In [29]:
df.isnull()     ####### TO find the missing values or null values

city  Temperature  humidity
0  False        False      True
1  False        False      True
2  False        False      True
3  False         True     False
4  False         True     False
5  False         True     False

In [30]:
df.isnull().sum()

city           0
Temperature    3
humidity       3
dtype: int64

In [32]:
df['Temperature']=df['Temperature'].fillna(df.Temperature.min())

In [33]:
df.isnull()

city  Temperature  humidity
0  False        False      True
1  False        False      True
2  False        False      True
3  False        False     False
4  False        False     False
5  False        False     False

In [34]:
df['humidity']=df['humidity'].fillna(df.humidity.min())

In [35]:
df.isnull()

city  Temperature  humidity
0  False        False     False
1  False        False     False
2  False        False     False
3  False        False     False
4  False        False     False
5  False        False     False

In [36]:
df

city  Temperature  humidity
0  New York         32.0      20.0
1   Chicago         45.0      20.0
2   Orlando         35.0      20.0
3    Mumbai         32.0      39.0
4        AP         32.0      46.0
5   Chennai         32.0      20.0

# missing values

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\YAMUNA\OneDrive\Documents\TEMP.csv")
df


Temperature  Humidity       city
0           34        50  Hyderabad
1           24        45  Hyderabad
2           34        36  Hyderabad
3           12        56  Hyderabad
4           67        78  Hyderabad
5           78        89    Chennai
6           89        78    Chennai

In [3]:
df.isnull()

Temperature  Humidity   city
0        False     False  False
1        False     False  False
2        False     False  False
3        False     False  False
4        False     False  False
5        False     False  False
6        False     False  False

In [4]:
df.isnull().sum()

Temperature    0
Humidity       0
city           0
dtype: int64

In [18]:
df_clean=df.dropna()
df_clean

Temperature  Humidity       city
0           34        50  Hyderabad
1           24        45  Hyderabad
2           34        36  Hyderabad
3           12        56  Hyderabad
4           67        78  Hyderabad
5           78        89    Chennai
6           89        78    Chennai

# MINI PROJECT ONE

# Reading data

In [21]:
import pandas as pd
df=pd.read_csv(r"C:\Users\YAMUNA\OneDrive\Documents\weather_data.csv")
df


Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy
5  06-01-2025        Mumbai             33          59     Rainy
6  07-01-2025       Chennai             34          61     Sunny
7  08-01-2025    Rajamundry             32          63    Cloudy
8  09-01-2025         Eluru             31          64     Rainy
9  10-01-2025    Anakapalli             29          62     Sunny

# exploring data

In [22]:
df.head()

Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy

In [24]:
df.tail()

Date        City  Temperature_C  Humidity_% Condition
5  06-01-2025      Mumbai             33          59     Rainy
6  07-01-2025     Chennai             34          61     Sunny
7  08-01-2025  Rajamundry             32          63    Cloudy
8  09-01-2025       Eluru             31          64     Rainy
9  10-01-2025  Anakapalli             29          62     Sunny

In [25]:
df.shape

(10, 5)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Date           10 non-null     object
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64 
 3   Humidity_%     10 non-null     int64 
 4   Condition      10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes


In [27]:
df[2:5]

Date          City  Temperature_C  Humidity_% Condition
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy

In [29]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [31]:
df.dtypes

Date             object
City             object
Temperature_C     int64
Humidity_%        int64
Condition        object
dtype: object

In [32]:
df.Date

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: Date, dtype: object

In [33]:
df['Date']

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: Date, dtype: object

In [34]:
df[['Date','Condition']]

Date Condition
0  01-01-2025     Sunny
1  02-01-2025     Sunny
2  03-01-2025    Cloudy
3  04-01-2025    Cloudy
4  05-01-2025     Rainy
5  06-01-2025     Rainy
6  07-01-2025     Sunny
7  08-01-2025    Cloudy
8  09-01-2025     Rainy
9  10-01-2025     Sunny

In [40]:
df['Date'][df['Condition']=='Rainy']


4    05-01-2025
5    06-01-2025
8    09-01-2025
Name: Date, dtype: object

In [41]:
df=pd.DataFrame({
    "name":["yamuna","devi","sai"],
    "age":[24,25,27]
})
df

name  age
0  yamuna   24
1    devi   25
2     sai   27

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [43]:
df.head()

name  age
0  yamuna   24
1    devi   25
2     sai   27

In [44]:
df.tail()

name  age
0  yamuna   24
1    devi   25
2     sai   27

In [45]:
df.shape

(3, 2)